const model = {
  html: {
    appDiv: document.getElementById("app"),
  },
  loot: [
    //gjøre om loot til et array med obj, consumables etc som et felt i hvert obj

    {
      name: "Waterbottle",
      category: "consumable",
      IMG: "someimage",
      icon: "someicon",
      id: 01,
      quality: "common",
      value: 20,
      HP: 20,
      description: "A cool, clear bottle of water.",
    },
    {
      name: "Stale loaf of bread",
      category: "consumable",
      IMG: "someimage",
      icon: "someicon",
      id: 02,
      quality: "common",
      value: 30,
      HP: 10,
      description: "Not very apetizing, but atleast its edable.",
    },
    {
      name: "Roasted leg of wolf",
      category: "consumable",
      IMG: "someimage",
      icon: "someicon",
      id: 03,
      quality: "uncommon",
      value: 60,
      HP: 50,
      description: "A fitting meal for a ruthless warrior.",
    },
    {
      name: "Rotten flesh",
      category: "consumable",
      IMG: "someimage",
      icon: "someicon",
      id: 04,
      quality: "poor",
      value: 0,
      hp: -10,
      description:
        "Rotten meat beyond any kind of recognition. What animal is this from? Are you sure it's animal at all? Only the bravest will dare eat this.",
    },
    {
      name: "The Letteropener",
      category: "weapon",
      IMG: "someimage",
      icon: "someicon",
      id: 11,
      quality: "poor",
      value: 10,
      bonusDamage: 6,
      description:
        "Better than bare hands... Maybe..... Hey at least its sharp... ish...",
    },
    {
      name: "The Smasher",
      category: "weapon",
      IMG: "someimage",
      icon: "someicon",
      id: 12,
      quality: "common",
      value: 20,
      bonusDamage: 10,
      description: "A common mace. Packs quite a punch, but clumsy to swing",
    },
    {
      name: "Tiny Tee",
      category: "armor",
      IMG: "someimage",
      icon: "someicon",
      id: 21,
      quality: "poor",
      value: 5,
      bonusArmor: 1,
      description:
        "A tiny, torn t-shirt. Better than being naked, but not by much",
    },
  ],

  inventory: {
    isOpen: false,
    contents: [],
  },
  backgrounds: [
    "IMG/Backgrounds/Background1.jpg",
    "IMG/Backgrounds/Background2.jpg",
    "IMG/Backgrounds/Background3.jpg",
    "IMG/Backgrounds/Background4.jpg",
    "IMG/Backgrounds/Background5.jpg",
    "IMG/Backgrounds/Background6.jpg",
    "IMG/Backgrounds/Background7.jpg",
    "IMG/Backgrounds/Background8.jpg",
  ],
  currentBackground: "",
  itemsByQuality: {},
};
