const model = {
  html: {
    appDiv: document.getElementById("app"),
  },
  loot: [
    //gjøre om loot til et array med obj, consumables etc som et felt i hvert obj

    {
      name: "Waterbottle",
      category: "Consumable",
      IMG: "IMG/Pictures/ItemPictures/Waterbottle.png",
      icon: "someicon",
      id: 01,
      quality: "Common",
      color: "white",
      value: 20,
      HealthPoints: 20,
      description: "A cool, clear bottle of water.",
    },
    {
      name: "Stale loaf of bread",
      category: "Consumable",
      IMG: "IMG/Pictures/ItemPictures/StaleLoafOfBread.png",
      icon: "someicon",
      id: 02,
      quality: "Common",
      color: "white",
      value: 30,
      HealthPoints: 10,
      description: "Not very apetizing, but atleast its edable.",
    },
    {
      name: "Bottle of murkwater",
      category: "Consumable",
      IMG: "someimage",
      icon: "someicon",
      id: 02,
      quality: "Poor",
      color: "grey",
      value: 10,
      HealthPoints: 5,
      description: "Keeps you hydrated. If you can keep it down.",
    },
    {
      name: "Roasted leg of wolf",
      category: "Consumable",
      IMG: "IMG/Pictures/ItemPictures/RoastedLegOFWolf.png",
      icon: "someicon",
      id: 03,
      quality: "Uncommon",
      color: "green",
      value: 60,
      HealthPoints: 50,
      description: "A fitting meal for a ruthless warrior.",
    },
    {
      name: "Grilled bearmeat",
      category: "Consumable",
      IMG: "IMG/Pictures/ItemPictures/GrilledBearmeat.png",
      icon: "someicon",
      id: 04,
      quality: "Uncommon",
      color: "green",
      value: 100,
      HealthPoints: 70,
      description: "Bear makes you strong!",
    },
    {
      name: "Rotten flesh",
      category: "Consumable",
      IMG: "IMG/Pictures/ItemPictures/RottenFlesh.png",
      icon: "IMG/Icons/rotten meat.jpg",
      id: 04,
      quality: "Poor",
      color: "grey",
      value: 0,
      HealthPoints: -10,
      description:
        "Rotten meat beyond any kind of recognition. What animal is this from? Are you sure it's animal at all? Only the bravest will dare eat this.",
    },
    {
      name: "The Letteropener",
      category: "Weapon",
      IMG: "IMG/Pictures/ItemPictures/TheLetteropener.png",
      icon: "IMG/Icons/dagger.jpg",
      id: 11,
      quality: "Poor",
      color: "grey",
      value: 10,
      bonusDamage: 6,
      description:
        "Better than bare hands... Maybe..... Hey at least its sharp... ish...",
    },
    {
      name: "The Smasher",
      category: "Weapon",
      IMG: "IMG/Pictures/ItemPictures/TheSmasher.png",
      icon: "someicon",
      id: 12,
      quality: "Common",
      color: "white",
      value: 20,
      bonusDamage: 10,
      description: "A common mace. Packs quite a punch, but clumsy to swing",
    },
    {
      name: "Knights blade",
      category: "Weapon",
      IMG: "IMG/Pictures/ItemPictures/KinghtsBlade.png",
      icon: "someicon",
      id: 13,
      quality: "Uncommon",
      color: "green",
      value: 30,
      bonusDamage: 40,
      description:
        "A blade fit for a champion. Although its former champion was slaughtered",
    },
    {
      name: "Soulblade",
      category: "Weapon",
      IMG: "IMG/Pictures/ItemPictures/Soulblade.png",
      icon: "someicon",
      id: 13,
      quality: "Rare",
      color: "blue",
      value: 80,
      bonusDamage: 90,
      description:
        "A master blade of precission. Handles like a feather. Cuts like a razor",
    },
    {
      name: "The Reaper",
      category: "Weapon",
      IMG: "IMG/Pictures/ItemPictures/Reaper.png",
      icon: "someicon",
      id: 14,
      quality: "Epic",
      color: "purple",
      value: 120,
      bonusDamage: 150,
      description:
        "A strange humming emits from this blade. It doesn't just kill you. It takes your soul",
    },
    {
      name: "Tiny Tee",
      category: "Armor",
      IMG: "IMG/Pictures/ItemPictures/TinyTee.png",
      icon: "someicon",
      id: 21,
      quality: "Poor",
      color: "gray",
      value: 5,
      bonusArmor: 1,
      description:
        "A tiny, torn t-shirt. Better than being naked, but not by much",
    },
    {
      name: "Titanium helmet",
      category: "Armor",
      IMG: "someimage",
      icon: "someicon",
      id: 22,
      quality: "Rare",
      color: "blue",
      value: 70,
      bonusArmor: 50,
      description:
        "Nothing will penetrate your skull with this helmet covering it. Almost nothing ...",
    },
    {
      name: "Mighty bulwark",
      category: "Armor",
      IMG: "someimage",
      icon: "someicon",
      id: 22,
      quality: "Epic",
      color: "purple",
      value: 250,
      bonusArmor: 100,
      description:
        "An enormous shield that will protect you from top to toe. Its made of some strange metal, because it's light as a feather.",
    },
  ],

  inventory: {
    isOpen: false,
    contents: [],
  },
  backgrounds: [
    "IMG/Backgrounds/Background1.jpg",
    "IMG/Backgrounds/Background2.jpg",
    "IMG/Backgrounds/Background3.jpg",
    "IMG/Backgrounds/Background4.jpg",
    "IMG/Backgrounds/Background5.jpg",
    "IMG/Backgrounds/Background6.jpg",
    "IMG/Backgrounds/Background7.jpg",
    "IMG/Backgrounds/Background8.jpg",
  ],
  currentBackground: "",
  itemsByQuality: {},
  itemTooltip: "",
  actionBox: "",
  health: 100,
  wallet: 0,
  currentLoot: [],
  lootDisplay: "",
  lootQueryDisplay: "",
};
